### ISSUE TITLE
Taking Knockback with Shield Up

### ISSUE THREAD

**Issue by Waffz** [Fabricators-of-Create/Create#1230]
### Describe the Bug

Player is taking Knockback from mobs even if the shield is being used

### Reproduction Steps

1. Have Shield up
2. Get attacked by mob
3. Take Knockback?

### Expected Result

This kind of behavior with shields does not happen in un-modded Minecraft.

### Screenshots and Videos

With Create Mod:
https://github.com/Fabricators-of-Create/Create/assets/74091942/432c6b28-be55-498c-968f-72d520e450e5

How it should work:

https://github.com/Fabricators-of-Create/Create/assets/74091942/183adba8-5db7-4b8b-9aef-e931e4498406

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Fabric API + Create was the only mods running during the test

**Comment by Kzi368** [comment]
It might be useful to know that getting hit by a wither with the shield up will negate the damage but not the wither effect. Blaze fireballs' fire also goes through the shield. Also, the issue seems to be solved in this branch: https://github.com/IThundxr-Modding/Create-Fabric/tree/mc1.20.1/fabric/dev

**Comment by TropheusJ** [comment]
this should be fixed in patch f
