### ISSUE TITLE
Сhests remain open

### ISSUE THREAD

**Issue by MightyBunch** [Fabricators-of-Create/Create#1441]
### Describe the Bug

When playing on server, sometimes, when exiting the chest, it visually remains open and no longer closes even when re-entering and exiting the chest.

### Reproduction Steps

1. Connect to server
2. Stand in ~4 blocks away from chest
3. Open the chest
4. Exit the chest
5. If it's closed, repeat (maybe from different position)

### Expected Result

Expected, that chest will be closed when it's closed.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/117296149/ca758217-beda-47fa-9f4e-78e8fa2189ae)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Additional Context

Tested without any other mods, just fabric api and create. Without create with just fabric api everything is normal. Appears frequently when standing far away from chest (not too far to be able to open the chest, obviously). Flywheel backend instancing, batching, off - nothing helps. With backend instancing, when double chest is betwheen chunks, only half of him remains open.

**Comment by TropheusJ** [comment]
this seems to be an issue with Reach Entity Attributes.
Chests check a box with radius 5 for players opening it, but REA changes that to account for extended reach.
There's an error in the logic somewhere, so it misses players standing right on the edge.
This is a minor visual issue that will naturally be fixed in 1.20.5+, so I don't really care to do anything about it.

**Comment by TropheusJ** [comment]
also, this has been always been an issue, back beyond 1.18. Nobody else has noticed so far.
