### ISSUE TITLE
X-Ray through windows

### ISSUE THREAD

**Issue by Eggmanplant** [Fabricators-of-Create/Create#1457]
### Describe the Bug

When you look at the bottom of windows, there is an x-ray effect.

### Reproduction Steps

1. Look at the bottom of windows

### Expected Result

Windows should work the same as do in the Forge edition of the mod

### Screenshots and Videos

![Screenshot from 2024-04-21 17-35-02](https://github.com/Fabricators-of-Create/Create/assets/126160675/ef14c670-1f31-4d5c-972d-0e742f1eb8ec)

### Operating System

Arch Linux

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

All mods from the Simply Optimized modpack

**Comment by NolanHewitt** [comment]
I've seen this as well, with the create's liquid storing tanks

**Comment by Eggmanplant** [comment]
Found an fix: Turn off modded block culling in MoreCulling config

**Comment by IThundxr** [comment]
This issue is not related to create and is caused by a addon mod/another mod.

Works fine with sodiums stricter culling and vanilla, more culling should not be forcefully culling blocks or atleast have a opt out that doesn't require you to compileOnly dependend on it, this issue also occurs with tracks and is really just moreculling being invasive.
