### ISSUE TITLE
Convert .obj files to Minecraft models

### ISSUE THREAD

**Issue by BugInYourCode01** [Fabricators-of-Create/Create#1475]
### Describe the Suggestion

You may have noticed from time to time that certain blocks are extremely slow in performance.

One reason could be that these blocks ([in these subfolders](https://github.com/Fabricators-of-Create/Create/tree/ae7df4b3c7097f3724d8a9b1ae66df48b54d509d/src/main/resources/assets/create/models/block)) are not saved in .json form (Minecraft model), but in an .obj file.
The conversion from 3d model to a format readable by minecraft takes unnecessary performance. I believe and am also quite sure that you can then achieve higher fps even with shaders and therefore without flywheel optimization.

**Comment by IThundxr** [comment]
It does not, there are models that cannot be made in minecraft's json format because of its limitations, create fabric uses porting libs obj loader which is a port of forge's obj loader which has existed for ages and no one has reported any performance issues caused by it, obj models do not affect performance
