### ISSUE TITLE
Fluid tank crash

### ISSUE THREAD

**Issue by eszdman** [Fabricators-of-Create/Create#248]
### Describe the Bug

When I tried to fill fluid tank using create mechanism's I got this crash log.

### Reproduction Steps

1.Create lava pump using create and connect it directly to fluid tank.
2.Try to change pump directions
3.Wait until it filled or empty

### Expected Result

Expected working fluid system

### Screenshots and Videos
![2022-04-16_17 25 56](https://user-images.githubusercontent.com/45270494/163678929-658aaa4d-8399-4b8f-9788-5286af4107b5.png)

Pipe should be instead of air.

### Crash Report or Log

https://pastebin.com/6XjyEvpC

### Operating System

Windows 10 x64

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

v0.4.1+497

**Comment by digitaltrucker** [comment]
Have you tried the latest build?  I'm running a lava pumping station with no problems using build 503.  The only difference between my system and yours is my storage tank is in the overworld.

**Comment by eszdman** [comment]
Same problem on build 504

**Comment by eszdman** [comment]
Trying firstly to fill it and then retract
![2022-04-16_20 02 30](https://user-images.githubusercontent.com/45270494/163684492-04f52bda-6eb2-41e0-ab14-1da320014875.png)

**Comment by digitaltrucker** [comment]
I just reproduced the crash also.

1:  Fill the tank
2:  Retract the hose pulley
3:  Reverse pump's direction
4:  Lower the hose pulley again
5:  Crash.

https://pastebin.com/GeJihNd5

**Comment by digitaltrucker** [comment]
It has to do with the hose pulleys, I think.  I just tried to empty an aquifer with just two hose pulleys and a pump and it crashed.

**Comment by TropheusJ** [comment]
Can't reproduce with these steps. Can I get a video of the process?

**Comment by anim4trix** [comment]
https://user-images.githubusercontent.com/96380963/164968507-20a54fcb-00dc-4ffe-bd59-9244c4781263.mp4

**Comment by digitaltrucker** [comment]
Just using a wrench to reverse the pump's direction while pumping triggers the crash for me.

**Comment by TropheusJ** [comment]
re-created video exactly, does not occur. Make sure you're on the latest build (510 as of writing). Since earlier versions had this issue, this might be residual messed up data. Do not test this on a pre-existing network; build a new one.

digitaltrucker experienced a different crash which has since been fixed, that may also be what's happening here.

**Comment by digitaltrucker** [comment]
Odd.  With Build 520 I did a quick test and the game crashed when I reversed the flow.  I was able to reload the world (an improvement) and wasn't able to get it to crash again.  So it's working good sorta?  Most of the time?  I don't know...

Crash log:  https://pastebin.com/FCbQaMLf
![2022-04-26_20 22 57](https://user-images.githubusercontent.com/77534286/165420029-0212c6d9-06e3-4566-90d0-681917bcb7b8.png)

**Comment by digitaltrucker** [comment]
Still crashy with latest build and latest Fabric loader.  Can't reload the crashed world either.

https://pastebin.com/VbfHYtLc

**Comment by digitaltrucker** [comment]
Using Build 534.  No more crashing, but fluid tanks fail to resume filling or emptying when reloading a single-player save.  Reversing the pump's direction does nothing.  Can only be fixed by breaking and replacing the fluid tanks, then everything works fine until the next save/quit/reload.  I think the issue was present before but crashiness prevented me from really investigating.

**Comment by TropheusJ** [comment]
can't reproduce. Break and replace all of the network. If it persists open a separate issue
