### ISSUE TITLE
Apotheosis uses newer Porting Lib, causing crash 

### ISSUE THREAD

**Issue by Gamerbolts** [Fabricators-of-Create/Create#326]
### Describe the Bug

I am creating a rather large modpack and included your mod and when I try to create a new world it crashes.

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Load the world

### Crash Report or Log

https://pastebin.com/tzUAEf7a

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Too many to paste here. This is my modpack google sheet

https://docs.google.com/spreadsheets/d/1S--Gsjqe4B8BPipKmOJVyV7nim12h63TUyKee_alI60/edit?usp=sharing

### Additional Context

Any help is appreciated. Thank you!

**Comment by Beleggrodion** [comment]
I also had a big list of mods (extended a exisitng modpack for playing on private server) and tried to add the create mod. An receive the same error message:

`NoSuchMethodError: 'net.minecraft.class_2487 io.github.fabricators_of_create.porting_lib.util.EntityHelper.getExtraCustomData(net.minecraft.class_1297)'`

https://crashy.net/EA8ePfIamo65lcUnqzNq (with create additions mod included, first suspected this mod)
https://crashy.net/aM2nKl4Ukkl0TLeVId95 (create additions mod removed)
https://crashy.net/1T0D1r4DfwRMDDQJEyM0 (betteranimalsplus and megaparrot removed because the crashs above suspected perhaps this two mods)

**Comment by Gamerbolts** [comment]
After some tireless testing. It seems like it is actually the update for Apotheosis. I am downgrading to the version before and will test it. I realized with your log we both had the same updated version.

*EDIT* Ok I can confirm. I put Apotheosis in, version 0.2.6 and it crashed. I downgraded to version 0.2.5 and it loaded no problems. Not sure if it is something with Create and Apotheosis or just that version of Apotheosis itself.

**Comment by Beleggrodion** [comment]
Looks like you have right, i checked their last changes between 0.2.5 and 0.2.6 and see that they updated the port lib dependencies from 0.2.0 to 1.1.0-beta: https://github.com/Safrodev/Apotheosis-Fabric/commit/48210709e25e6bab095164d37ee36c8c75f2da0b 

Perhaps their is a conflict between the packed portlib in create with the packed portlib in Apotheosis? Because both use now the same version?

**Comment by TropheusJ** [comment]
They appear to use the same version, but they’re on different hashes. Create is using an older one, and we broke some stuff recently and need to update Create.

**Comment by TropheusJ** [comment]
this should be resolved
