### ISSUE TITLE
Incorrect culling with More Culling installed

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#479]
### Describe the Bug

it doesnt render the blockface that it is sitting on, despite being a transparent

### Reproduction Steps

1.use this modpack: https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659
2.update create (remove addons that are outdated)
3.issue
...

### Expected Result

To render normally

### Screenshots and Videos

![Uploading image.png…]()

### Crash Report or Log

https://gist.github.com/FluffyBumblebees/3fefc9ab56db82adfc5dd53a888f95af

### Operating System

Win 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Listed on the modpack page

### Additional Context

it's not shaders, tested without it

**Comment by TropheusJ** [comment]
mod incompatibility, try to narrow it down

**Comment by StockiesLad** [comment]
Ok, I'd guess indium/sodium but I'll test once create additions is updated (so that my modpack doesnt break)

**Comment by StockiesLad** [comment]
Add this to low priority for now

**Comment by StockiesLad** [comment]
It is more culling

**Comment by StockiesLad** [comment]
![image](https://user-images.githubusercontent.com/60066663/182866995-86f94e34-5e89-44b2-9f08-8e967bda8fdf.png)

**Comment by FxMorin** [comment]
Ok so this is due to the culling shape of the track being a flat box. The call to `getOcclusionShape()` returns the culling shape of the track, its not used so `getShape()` is used instead. As you can see [here](https://github.com/Fabricators-of-Create/Create/blob/f367d529aa69c1e3e3dc18c57d041a49eb377437/src/main/java/com/simibubi/create/content/logistics/trains/track/TrackBlock.java#L484) it then gets the correct voxel for this track.
[The Voxel](https://github.com/Fabricators-of-Create/Create/blob/f367d529aa69c1e3e3dc18c57d041a49eb377437/src/main/java/com/simibubi/create/AllShapes.java#L150) leads to [here](https://github.com/Fabricators-of-Create/Create/blob/f367d529aa69c1e3e3dc18c57d041a49eb377437/src/main/java/com/simibubi/create/content/logistics/trains/track/TrackVoxelShapes.java#L10) where you can see its just a flat box.
This is not the correct culling shape based on what the track looks like.

There are multiple ways to fix this:
1) Use the correct culling shape. This can help other rails next to the rail cull!
2) Use the block tag: `moreculling:dont_cull`
3) Use the moreculling API to set `cantCullAgainst()` to prevent culling against the block while still allowing the rails to cull themselves against other blocks

If you do option 3, you can also use the API to set `customShouldDrawFace()` so that the rails cull against themselves.
Otherwise please set `isSideInvisible` to do that.

With a long rail setup, culling these faces can really help out

**Comment by StockiesLad** [comment]
> Ok so this is due to the culling shape of the track being a flat box. The call to `getOcclusionShape()` returns the culling shape of the track, its not used so `getShape()` is used instead. As you can see [here](https://github.com/Fabricators-of-Create/Create/blob/f367d529aa69c1e3e3dc18c57d041a49eb377437/src/main/java/com/simibubi/create/content/logistics/trains/track/TrackBlock.java#L484) it then gets the correct voxel for this track. [The Voxel](https://github.com/Fabricators-of-Create/Create/blob/f367d529aa69c1e3e3dc18c57d041a49eb377437/src/main/java/com/simibubi/create/AllShapes.java#L150) leads to [here](https://github.com/Fabricators-of-Create/Create/blob/f367d529aa69c1e3e3dc18c57d041a49eb377437/src/main/java/com/simibubi/create/content/logistics/trains/track/TrackVoxelShapes.java#L10) where you can see its just a flat box. This is not the correct culling shape based on what the track looks like.
> 
> There are multiple ways to fix this:
> 
> 1. Use the correct culling shape. This can help other rails next to the rail cull!
> 2. Use the block tag: `moreculling:dont_cull`
> 3. Use the moreculling API to set `cantCullAgainst()` to prevent culling against the block while still allowing the rails to cull themselves against other blocks
> 
> If you do option 3, you can also use the API to set `customShouldDrawFace()` so that the rails cull against themselves. Otherwise please set `isSideInvisible` to do that.
> 
> With a long rail setup, culling these faces can really help out

I'll KJS the blocktag for a temp fix

**Comment by IThundxr** [comment]
Seems to already be fixed
