### ISSUE TITLE
Inconsistent crafting on Belt with normal Chute at higher speed

### ISSUE THREAD

**Issue by Gabriel-Fluffy** [Fabricators-of-Create/Create#522]
### Describe the Bug

When placing a stack of items on a belt with a normal Chute and a belt speed higher than 80rpm items passing under deployers or mechanical presses are sometimes ignored and pass on without beeing processed. This does not happen with smart chutes or funnels.

### Reproduction Steps

1. Build a production line with a belt speed higher than 80 rpm
2. Deploy the items on the belt with a normal chute
3. Some items will pass under presses or deployers without being processed

### Expected Result

All items should be processed. (Works in the forge version)

### Screenshots and Videos

https://user-images.githubusercontent.com/91908724/185792877-d6ce0165-84d8-45b8-921a-6086165a86a3.mp4

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

fabric-api-0.58.0+1.18.2.jar

**Comment by TropheusJ** [comment]
Can't reproduce, maybe fixed. Could you test with a [dev build](https://github.com/Fabricators-of-Create/Create/actions/runs/2950338012)?

**Comment by Gabriel-Fluffy** [comment]
just tested it with the dev build and i still have the problem

**Comment by TropheusJ** [comment]
Can’t reproduce, please test patch G.

**Comment by artemisSystem** [comment]
I'm having a similar issue with this setup. I think it's the same cause but easier to see since it's going slower. What happens is the deployer goes down, but the item moves past it just before it hits. (Perfectly caught in this screenshot). I just give the deployers materials for the precision mechanism, and then put 2 gold sheets in the leftmost hopper. After a cycle or so, the bug appears

![2022-11-27_13 18 18](https://user-images.githubusercontent.com/39034386/204135043-a2d2dec0-6def-4903-baf2-aef5e5f171ab.png)

The bottom belt is going -8 rpm (rightwards), top belt is going 8 rpm (leftwards), deployers also 8 rpm

Using create-fabric-0.5.0g-791+1.19.2

**Comment by TropheusJ** [comment]
can't reproduce, I think this was fixed at some point
