### ISSUE TITLE
Config for Potion Recipes

### ISSUE THREAD

**Issue by Shadowdragon019** [Fabricators-of-Create/Create#557]
### Describe the Suggestion

A config option to remove recipes that involve recipes, as they're hard-coded & I can't remove them without coding.

I want this as in my modpack I don't want potion recipes as I'm focusing on automation.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/67480398/190853714-f0b5fe9b-856d-447f-9950-ef9c8fc012b1.png)
![image](https://user-images.githubusercontent.com/67480398/190853717-ba2963dc-28f7-460e-9db6-9dc2b429ab7c.png)

**Comment by JieningYu** [comment]
please request features in Create Forge's repo.

**Comment by Shadowdragon019** [comment]
Alright

**Comment by DarianLStephens** [comment]
I'd like to know a bit more about your rationale there.
You don't want to be able to automate potion recipes... because your pack focuses on automation?
Why remove a way to automate something when the point is automation? You should also remember that Create has recipes that require potions as part of them, sprayed as a liquid.

**Comment by TropheusJ** [comment]
Gameplay suggestions should be made to the forge repo
