### ISSUE TITLE
Support for Drop Z

### ISSUE THREAD

**Issue by netcore10** [Fabricators-of-Create/Create#595]
### Describe the Suggestion

I believe dropz uses custom entity for drops, would be great to support it!

https://github.com/LazuriteMC/Dropz/issues/25

### Screenshots and Videos

See dropz issue, i don't think they can do it on their end.

### Additional Context

Dropz uses the rayon physics api.

**Comment by Brickmaster1** [comment]
Seconding, I have been wanting this forever...

**Comment by const-fn** [comment]
I've found that the issue lies in the rayon physics api that dropz uses.
It disables (return at head) the move method in the entity class for every physics element.
Removing that patch in the rayon library fixes issues with create (and other mods).
I can't say if that causes any side effects, at least I have experienced anything.

**Comment by Brickmaster1** [comment]
Oh, interesting, it is probably an easy fix to being able to push the entities or something, that's my guess. But I feel like simply redirecting to the rayon method would be better. Not sure.

**Comment by IThundxr** [comment]
DropZ is abandoned/archived

**Comment by Brickmaster1** [comment]
Yes, it is now, lol, this is an old issue haha
