### ISSUE TITLE
Incompatible with OptiFabric

### ISSUE THREAD

**Issue by rctts** [Fabricators-of-Create/Create#616]
### Describe the Bug

The game doesn't load up when having Create mod installed with Optifabric

### Reproduction Steps

These are the mods I had installed:

create-fabric-1.18.2-0.5.0e-733.jar
fabric-api-0.67.0+1.18.2.jar
modmenu-3.2.4.jar
optifabric-1.13.16.jar
OptiFine_1.18.2_HD_U_H7.jar
voicechat-fabric-1.18.2-2.3.15.jar
Xaeros_Minimap_22.16.2_Fabric_1.18.2.jar

### Expected Result

The game loading up normally with all mods successfully loaded

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/49565903/203133494-810121a3-2609-40f6-924c-7232090377bb.png)

### Crash Report or Log

https://pastebin.com/WGLw0Mr1

### Operating System

Windows 10

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

fabric-api-0.67.0+1.18.2.jar
modmenu-3.2.4.jar
optifabric-1.13.16.jar
OptiFine_1.18.2_HD_U_H7.jar
voicechat-fabric-1.18.2-2.3.15.jar
Xaeros_Minimap_22.16.2_Fabric_1.18.2.jar

**Comment by AlphaMode** [comment]
Optifabric support will never happen. The amount of changes needed to even make the two work together is too large. It is also nearly impossible to debug the two mods due to optifine being closed source. Fabric has way better alternatives such as Sodium and Iris. Which I highly recommend you use instead. They both have really good mod compatibility.

**Comment by rctts** [comment]
ill have to try em out then, ty for getting back aswell! :D
