### ISSUE TITLE
1.19dev EMI missing some recipes

### ISSUE THREAD

**Issue by artemisSystem** [Fabricators-of-Create/Create#629]
### Describe the Bug

The recipe for deploying andesite alloy onto a stripped log (making andesite casing) is missing from EMI.
Additionally, the world interaction recipe for crafting andesite casing by clicking a stripped log with andesite alloy is also not visible.

Both recipes still seem to function as normal.

### Reproduction Steps

1. Click "find recipes" on an andesite alloy
2. No menu opens, because there are no recipes

### Expected Result

Expected to see a deploying recipe and a world interaction recipe

### Operating System

macOS 13.1

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by artemisSystem** [comment]
Also seems to be missing sequenced assembly recipes

**Comment by artemisSystem** [comment]
Nevermind, the issue may be on my end

**Comment by deli73** [comment]
> Nevermind, the issue may be on my end

any insight as to what the issue might be, then? we're experiencing it too; all manual application and sequenced assembly recipes seem to be missing.

**Comment by artemisSystem** [comment]
i'm using an unreleased preview version of EMI, have yet to try a normal release. i'm also using quilt

**Comment by Timongcraft** [comment]
I also have this bug I'm on windows 10 using the latest 1.19.2 version of create-fabric and emi but I also had it without emi.

**Comment by sylv256** [comment]
also having this issue on 1.19.2 quilt w/ EMI, but it's only not displaying stuff for things like the Potato Canon and Casing

**Comment by maximumpower55** [comment]
Do any of y'all have farmers delight installed when these issues occur, since farmers delight breaks create's EMI plugin due to a broken filling recipe

**Comment by artemisSystem** [comment]
Ah, yes. I have FD and FD's emi support installed

**Comment by maximumpower55** [comment]
> Ah, yes. I have FD and FD's emi support installed

That's your issue, good thing this can be fixed with a simple datapack, I would report this to FD and close this issue

**Comment by Timongcraft** [comment]
I also had FD installed but after I took it out I still can't see recipes from like crushing wheels ore the casings.

**Comment by LemmaEOF** [comment]
For the record, TL;DR on *how* FD breaks EMI:
- FD adds a create compat recipe for spouting chocolate into piecrusts to make chocolate pie
- That recipe uses the `c:chocolates` fluid tag
- Create puts chocolate fluid in the `c:chocolate` fluid tag, not `c:chocolates`
- This results in the recipe getting an empty fluid tag for spouting, meaning there are zero valid fluids
- Create's EMI plugin assumes there is at least one valid fluid, because spouting recipes inherently require fluid
- When trying to load a spouting recipe it looks for the first fluid in the list of valid fluids
- This results in an `ArrayIndexOutOfBoundsException` being thrown when the list is empty
- Because recipes are added into EMI as they're processed, this means that anything loading after that recipe doesn't get added
