### ISSUE TITLE
Some recipes have incorrect or missing items

### ISSUE THREAD

**Issue by CoreBytee** [Fabricators-of-Create/Create#651]
### Describe the Bug

Some items are missing from a few recipes in the new 0.5g patch 1 version.

### Reproduction Steps

1. Download 0.5.0g patch 1
2. Download EMI
3. Open world
4. View recipe of Precision mechanism
5. Last step is missing

### Expected Result

Items are not missing from recipes

### Screenshots and Videos

https://i.corebyte.me/6xh8
https://i.corebyte.me/8ZLU

### Operating System

Ubuntu 20

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Full list: https://i.corebyte.me/8uVAQ

### Additional Context

Using 0.5.0g patch 1

**Comment by KennyLee2378** [comment]
Experiencing same bug in a server I own, however for some reason relaunching and going into singleplayer beforehand sometimes fixes the issue. I think it might just be a loading problem.

**Comment by Hancoki** [comment]
I have still the same issue while using version 0.5.0i-1003+1.19.2. Also the iron nugget is shown as 'invalid'.

**Comment by Polarite** [comment]
issue still persists and cant craft the precision mechanism at all.

**Comment by jenchanws** [comment]
If you have the [Create: Extended Cogwheels](https://modrinth.com/mod/extended-cogwheels) mod, it's most likely due to the included recipe [`create:sequenced_assembly/precision_mechanism`](https://github.com/Rabbitminers/Extended-Cogwheels/blob/multiloader-1.18.2/fabric/src/main/resources/data/create/recipes/sequenced_assembly/precision_mechanism.json#L49) referring to the tag `c:nuggets/iron`, following Forge convention, instead of the Fabric convention `c:iron_nuggets`.

I don't think this has to do with Create Fabric at all, but I can't access the files in the original issue to verify.

Quick fix would be to add a datapack with [the fixed recipe](https://gist.github.com/jenchanws/81dcd42155ff20dda9c1158b49083b45) to your world or server.

**Comment by Polarite** [comment]
yep, thats all right except I had to change line 4 to
    "tag": "c:gold_plate"
since thats fabric convention.

for the future reference,

 thanks for the help.

**Comment by BitHeaven-Official** [comment]
Wrench crafts using only 3 gold sheets and 1 gear, but need using crafting table, earlier used + 1 stick

**Comment by BitHeaven-Official** [comment]
I have same problem with broken crafts on latest version 1017
Minecraft 1.19.2 fabric
Use JEI for watch recpies

**Comment by SteveNichols5** [comment]
> If you have the [Create: Extended Cogwheels](https://modrinth.com/mod/extended-cogwheels) mod, it's most likely due to the included recipe [`create:sequenced_assembly/precision_mechanism`](https://github.com/Rabbitminers/Extended-Cogwheels/blob/multiloader-1.18.2/fabric/src/main/resources/data/create/recipes/sequenced_assembly/precision_mechanism.json#L49) referring to the tag `c:nuggets/iron`, following Forge convention, instead of the Fabric convention `c:iron_nuggets`.
> 
> I don't think this has to do with Create Fabric at all, but I can't access the files in the original issue to verify.
> 
> Quick fix would be to add a datapack with [the fixed recipe](https://gist.github.com/jenchanws/81dcd42155ff20dda9c1158b49083b45) to your world or server.

Attaching a fully working version of the datapack that works to fix the precision mechanism

[precision_mechanism_fix_5.zip](https://github.com/Fabricators-of-Create/Create/files/11715701/precision_mechanism_fix_5.zip)

**Comment by Polarite** [comment]
item: golden_sheet could be changed to tag: gold_plate for the compatibility reasons but yes, that does fix the issue, this can be closed.
