### ISSUE TITLE
Fluid Tank's NBT data is ignored when placed on existing Fluid Tank

### ISSUE THREAD

**Issue by CzechHek** [Fabricators-of-Create/Create#690]
### Describe the Bug

If you place a Fluid Tank with NBT data (containing a fluid) on top of another Fluid Tank, its contents (NBT data) gets ignored.
This doesn't happen on Create Forge.

### Reproduction Steps

1. Place a Fluid Tank
2. Place a different fluid tank, put a liquid into it and pick it up with CTRL + middle mouse click
3. Place the fluid tank with NBT data on top of the first fluid tank

### Expected Result

Create Forge: https://youtu.be/8TatW1hOBjw

### Screenshots and Videos

Create Fabric: https://youtu.be/s-XmPCm25w8

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

none

**Comment by TropheusJ** [comment]
On Forge, all items are placed during block snapshots, so the state isn't updated immediately. The data is updated, then the block updates, so the 2 tanks merge.
On Fabric, the tanks merge as soon as the second one is placed. When the NBT is loaded, since the tank is not a controller, it just doesn't load the data.
