### ISSUE TITLE
Cannot join multiplayer map

### ISSUE THREAD

**Issue by michaeo1** [Fabricators-of-Create/Create#718]
### Describe the Bug

When trying to join friends world, am presented with the following error:

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 4036, length: 97 (expected:range(0, 4062))

### Reproduction Steps

1.Launch game using curse forge
2.Select Multiplayer
3.Attempt to join game, am presented with above error
...

### Expected Result

If possible please provide a way to resolve this

### Screenshots and Videos

![Untitled](https://user-images.githubusercontent.com/121595118/209903905-4a458e9e-f4c2-489a-86d7-5676e970a7dc.png)

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
your Create versions do not match.

**Comment by michaeo1** [comment]
That does not appear to be the case. Both myself and the host are running the latest update of the game through CurseForge and verified that our create (Create Chunkloading and Create Fabric) are the exact same (createchunkloading-1.3.0-fabric.jar and create-fabric-0.5.0g-796+1.19.2.jar respectively).

Is it possible I am looking at the wrong create? 

Please advise


![image](https://user-images.githubusercontent.com/121595118/209905114-f751470d-7628-449e-bcd5-37c0f99dee96.png)
![20221229_004803](https://user-images.githubusercontent.com/121595118/209905115-c4589857-3e76-4645-83ef-4219337c8c92.jpg)

**Comment by mdoary** [comment]
@TropheusJ please review update.

**Comment by michaeo1** [comment]
Added comment to clarify the situation. Create version do infact match
between myself and the host. Please see comment on github for further
detail.

**Comment by TropheusJ** [comment]
I need a log from both you and the host.

**Comment by mdoary** [comment]
Will donin the morning. Thank you

**Comment by mdoary** [comment]
[Hosts-logs.zip](https://github.com/Fabricators-of-Create/Create/files/10319776/Hosts-logs.zip)
[logs.zip](https://github.com/Fabricators-of-Create/Create/files/10319865/logs.zip)
Zip is the client

**Comment by TropheusJ** [comment]
does it work with Create alone? if not, you'll need to narrow down the cause. a 500 mod pack is not debuggable. Do a binary sort.
Split the mods in half. Fixed? Try the other half. Still happens? Split again. Repeat until mod that causes it is found.

**Comment by erikpaasonen** [comment]
also seeing this same behavior, though we're getting slightly more info in our error:
![Screenshot](https://user-images.githubusercontent.com/17558034/213176854-7238da81-0a67-4615-b4bb-e50a56087c1f.png)

only one other mod (Carpet) besides Fabric API; reproducible consistent with enabling/disabling Create independent of whether Carpet is also enabled or disabled.

we're on a dedicated server with less than 5 players, all of whom are running Linux and most have Create (the Fabric port, since we also run Carpet). I'm an experienced technical player but new to being a server admin and we're new to Create mod.

this user was previously able to join and play normally. it may or may  not be relevant, but the last thing he remembers doing is looting a shipwreck chest for its treasure map, which he confirms was in his inventory before getting disconnected. now every attempt to join the server with the Create mod loaded results in this error. 

both other players on the server are able to play normally with the same Create mod version. server logs show he connects and then immediately disconnects:
> [18.01 08:01:34] [Server] [User Authenticator #32/INFO]: UUID of player player1 is asdf-asdf-asdf
> [18.01 08:01:34] [Connect] player1, IP 1.2.3.4
> [18.01 08:01:34] [Server] Server thread/INFO]: player1 joined the game
> [18.01 08:01:34] [Multicraft] player1 ran command Message of the Day
> [18.01 08:01:35] [Disconnect] player1 has disconnected, reasonDisconnected
> [18.01 08:01:35] [Server thread/INFO]: player1 left the game

he can join the server by simply disabling the Create mod. first time he did so he found himself drowned in the shipwreck by the loot chest.

interestingly, I had this player authenticate on the computer of another player from this server (this one is Ubuntu 22.04.1 LTS). known-good Create mod setup. reproduced the user's issue with the same error, same disconnect after 1 second. main user of the machine is able to login and play on the server as normal.

is there anything I can do to the user's player data on the server to help flush this?

### Operating System

Linux (Pop!_OS 22.04 LTS)

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

- Carpet 1.4.84
- Fabric API 0.72.0

**Comment by TropheusJ** [comment]
Be 100% sure they are using the same version of create as the server

**Comment by erikpaasonen** [comment]
Server: `create-1.19.2-0.5.0.g.jar`
POP OS client: `create-fabric-0.5.0g-796+1.19.2.jar`
looks like the one disconnecting has 0.5.0 Patch 1 installed. will get patch 1 up on the server now and get the others to upgrade as well.

could patch 1 be re-released as 0.5.1 perhaps? proper semver would have made this issue more obvious up front.

**Comment by TropheusJ** [comment]
We need to stick with forge’s versioning. 0.5.1 will be the next content update, and 0.5h is the next bug fix update. 
> Server: `create-1.19.2-0.5.0.g.jar`

something isn’t right, because that’s a forge jar.

**Comment by erikpaasonen** [comment]
pinning to upstream versioning makes sense. thank you for explaining. :+1: 

ahh that explains quite a bit of the trouble we've been having getting Create to load on all players' systems. now that I uploaded `create-fabric-0.5.0g-796+1.19.2.jar` to the server and restarted it, it looks like Create works on all of them now! thank you!

hopefully this fixes @michaeo1 's problem as well, if so I'd suggest closing this issue.

**Comment by erikpaasonen** [comment]
spoke too soon. the player actually experiencing the issue is still disconnecting after 1sec with the same error I posted above. so, confirmed the server and client are both running `create-fabric-0.5.0g-796+1.19.2.jar` (patch 1).

EDIT: add fresh screenshot
![image](https://user-images.githubusercontent.com/17558034/213228576-3fd1240c-ebb3-46f8-a809-03579d6be791.png)

**Comment by TropheusJ** [comment]
Is this still a problem? Does it only affect 1 person? I need their full log.

**Comment by erikpaasonen** [comment]
in our case, it started affecting multiple people on our server, so we stopped playing with the Create mod enabled on this particular server. chances are the OP is in a similar situation. :)

I strongly suspect it is simply a matter of the server side running out of RAM and crashing+restarting the game instance. this has been run on a rented SaaS server with only 2GB of RAM, and the SaaS platform's recommendation for vanilla 1.19 is 4GB (grandfathered server from earlier versions I just never upgraded). going forward we're running servers locally with far more RAM and the plan is to migrate this one off of SaaS to local hardware soon, time permitting.

it's probably not fair to the maintainer(s) of this project to ask you to troubleshoot an issue we're having when we're not even using the minimum recommended system specs.

**Comment by TropheusJ** [comment]
this is a generic packet error that can be caused by pretty much anything. There's nothing to go off of to troubleshoot this. It's been over a year, hoping it's resolved itself
