### ISSUE TITLE
Curved track destruction does not check permissions

### ISSUE THREAD

**Issue by alimkoca** [Fabricators-of-Create/Create#727]
### Describe the Bug

When you hit the blocks comes from mod  *Create* really fast in claimed area (only tested on FLAN), it makes
possible to break without permissions, currently tested on *Create* tracks (rails).

### Reproduction Steps

1. Find a claimed area which isn't claimed by you.
2. Make owner of claimed area put a *Create* block (as I said, only tested on tracks).
3. Try breaking block fast as possible.

### Expected Result

You must be able to break blocks when you do that.

### Screenshots and Videos

![Screenshot from 2022-12-30 18-47-32](https://user-images.githubusercontent.com/66552942/210110881-9254d765-ab96-4143-b6b4-7f68ed2ccffe.png)

### Operating System

Fedora 6.0.15 GNU/Linux

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

**Comment by booleancoercion** [comment]
We play on the same server and I have a small addition:
You don't have to break the tracks quickly - this just works for any rail that wasn't placed as a solid block (for example turns, bends, slopes). The break event seems to bypass any permission API, since we also checked with Ledger and there's no block break event for any of the... entities? that compose the tracks.

Also, MC version is 1.18.2
