### ISSUE TITLE
Duplicated goggle tooltips with Double Hotbar

### ISSUE THREAD

**Issue by bebrickguy** [Fabricators-of-Create/Create#790]
### Describe the Bug

On minecraft server(aternos) few bogs with this
I dont know how to deal with it, but its making hard to read anything.

### Reproduction Steps

1.Look at any block of mode that have info for glasses

### Expected Result

To make there onlu on2 interface of glasses.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/124287815/216384991-50262d12-517a-4bd7-890f-acd10aee8fda.png)
![image](https://user-images.githubusercontent.com/124287815/216385236-b4302a99-703d-4ca4-b272-5df0becc3385.png)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

(Server mods)
adventurez-1.4.17.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
bclib-2.1.5.jar
better-end-2.1.2.jar
better-nether-7.1.2.jar
BetterAdvancements-Fabric-1.19.2-0.3.0.148.jar
Bookshelf-Fabric-1.19.2-16.2.17.jar
BotanyPots-Fabric-1.19.2-9.0.26.jar
BotanyTrees-Fabric-1.19.2-5.0.4.jar
charm-fabric-1.19.2-4.4.4.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
create-fabric-0.5.0g-796+1.19.2.jar
CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
culinaryconstruct-fabric-5.0.0-beta.1+1.19.2.jar
fabric-api-0.73.0+1.19.2.jar
ItemPhysic_FABRIC_v1.6.6_mc1.19.2.jar
Paintings-fabric-1.19.2-10.2.4.0.jar
RoughlyEnoughItems-9.1.526.jar

**Comment by TropheusJ** [comment]
Some mod incompat on your client. Try to narrow it down.

**Comment by ML1150** [comment]
It looks like you are using [double hotbar](https://www.curseforge.com/minecraft/mc-mods/double-hotbar), I got the same problem and it was resolved when removing this mod.
For me it was working just fine until yesterday when i started noticing the issue. It was only bugged in survival mode and the only difference I can find between survival and creative mode is the health-, hunger- & xp bars.

I really like the double hotbar so it would be nice if someone got a solution/fix.

**Comment by sidezbros** [comment]
Double Hotbar developer here. I have looked into the issue and it is a bug with create. I explain in the issue on my repository [here](https://github.com/sidezbros/double_hotbar/issues/17#issuecomment-1641239605), but long story short is that create is rendering this tool tip twice. Double Hotbar is just revealing the bug and there is nothing I can do to fix it. For greater compatibility with any mods that change the HUD, create should only render the tooltip once.

**Comment by sidezbros** [comment]
**This is an issue regardless if you use double hotbar.**

You can see evidence of the double tooltip render with and without Double Hotbar enabled. Even when the text is legible, the background is too dark because the tooltip is being rendered on top of itself. When double hotbar reveals the two layers, look at the difference in the color. Where they overlap it is too dark (bugged behavior by create). You can see the correct background color where they do not overlap. Now look at the tooltip when double hotbar is disabled. It is all too dark.

For any double hotbar fans following this: there is an option in the DH settings to show the second hotbar. Turning this off will hide the create issue at the cost of seeing the second hotbar. Everything else will still work, but you will not be able to see the top bar. This is unideal but better than having to uninstall the mod.

![DoubleHotbarOff](https://github.com/Fabricators-of-Create/Create/assets/20784865/7762d0f2-0116-4f79-886f-d522d5c1836c)
![DoubleHotbarOn](https://github.com/Fabricators-of-Create/Create/assets/20784865/d3af405b-2fe9-4b25-a375-591501e7a689)

@TropheusJ are you able to help us out with this?

Thanks everyone!

**Comment by QianFuv** [comment]
@TropheusJ plz check！

**Comment by TropheusJ** [comment]
this should be fixed
